### ISSUE TITLE
Feature request: edit NSUserDefaults / Keychain

### ISSUE THREAD

**Issue by sarsonj** [dbukowski/DBDebugToolkit#21]
Hi,

it is sometimes helpful to be able to edit NSUserDefaults and Keychain items within the app. Do you plan to add this feature?

Thanks,

Jidrich

**Comment by dbukowski** [comment]
Hey! Thanks, that’s a nice suggestion. The UI for that should be easy, as I could reuse the components from Custom Variables. The only tricky part could be saving the keychain values, but it should not be too difficult. I’ll take a look at it after going back from vacation at the end of August.

**Comment by zhugexiaobo** [comment]
Hi, could you also add the feature to export files in sandbox please? It should be helpful.

**Comment by dbukowski** [comment]
First of all, sorry for a late response. 

I took a look at that feature and unfortunately, it is way more complicated than I initially thought, mainly because of the multiple data types that it would need to support. I don't think I will be able to work on that issue. I will be looking for someone to help me maintain the library. In the meantime, the PRs are welcome! 😉 

Also, @zhugexiaobo, could you open a separate issue for that? If so, please describe it in more details, as I'm not quite sure what you mean by that. Thanks!

**Comment by gamada-de** [comment]
Topic is to old and will be closed.
